jobs:
- template: wcf-base.yml
  parameters:
    isOfficialBuild: ${{ parameters.isOfficialBuild }}
    jobs:

    # Legs with Helix testing
    - job: WindowsTest
      displayName: Windows
      timeoutInMinutes: 60
      pool:
        ${{ if eq(parameters.isOfficialBuild, 'false') }}:
          name: NetCorePublic-Pool
          queue: buildpool.windows.10.amd64.vs2017.open
        ${{ if eq(parameters.isOfficialBuild, 'true') }}:
          name: NetCoreInternal-Pool
          queue: buildpool.windows.10.amd64.vs2017
      strategy:
        matrix:
          Build_Release:
            _BuildConfig: Release
            # PRs or external builds are not signed.
            ${{ if eq(parameters.isOfficialBuild, 'false') }}:
              _SignType: test
              _DotNetPublishToBlobFeed : false
            ${{ if eq(parameters.isOfficialBuild, 'true') }}:
              _SignType: real
              _DotNetPublishToBlobFeed : true
              _WcfPRServiceId: 1
          ${{ if eq(parameters.isOfficialBuild, 'false') }}:
            Build_Debug:
              _BuildConfig: Debug
              _SignType: test
              _WcfPRServiceId: 2
